# Generated by Django 5.0.4 on 2024-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=300)),
                ('age', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('boolean', models.BooleanField()),
            ],
        ),
    ]
